# Generated by Django 3.2 on 2022-07-24 05:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SchSocialMedia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peopleinfo',
            old_name='book',
            new_name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.CharField(default=django.utils.timezone.now, max_length=300, verbose_name='文章内容'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ArticleComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, null=True, verbose_name='文章评论')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchSocialMedia.article', verbose_name='文章')),
            ],
            options={
                'verbose_name': '文章评论',
                'db_table': 'articlecomments',
            },
        ),
    ]
