# Generated by Django 3.2 on 2022-07-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schSocialMedia', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='articlecomments',
            options={'verbose_name': '文章评论', 'verbose_name_plural': '文章评论'},
        ),
        migrations.AlterModelOptions(
            name='peopleinfo',
            options={'verbose_name': '人物信息', 'verbose_name_plural': '人物信息'},
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(max_length=300, verbose_name='文章内容'),
        ),
    ]
