# Generated by Django 3.2 on 2022-07-25 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schSocialMedia', '0003_auto_20220725_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomments',
            name='pub_date',
            field=models.DateField(auto_now=True, verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now, verbose_name='发布日期'),
            preserve_default=False,
        ),
    ]
