# Generated by Django 3.2 on 2022-07-28 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schSocialMedia', '0008_auto_20220728_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-pub_date'], 'verbose_name': '房间管理', 'verbose_name_plural': '房间管理'},
        ),
        migrations.RemoveField(
            model_name='room',
            name='descripton',
        ),
        migrations.AddField(
            model_name='room',
            name='commentcount',
            field=models.IntegerField(default=0, verbose_name='评论量'),
        ),
        migrations.AddField(
            model_name='room',
            name='content',
            field=models.TextField(default=django.utils.timezone.now, max_length=600, verbose_name='描述'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='逻辑删除'),
        ),
        migrations.AddField(
            model_name='room',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='发布时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='readcount',
            field=models.IntegerField(default=0, verbose_name='阅读量'),
        ),
        migrations.AddField(
            model_name='room',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
