# Generated by Django 3.2 on 2022-07-29 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schSocialMedia', '0010_auto_20220728_2354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-pub_date'], 'verbose_name': '信息管理', 'verbose_name_plural': '信息管理'},
        ),
    ]
