# Generated by Django 3.2 on 2022-08-01 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schSocialMedia', '0011_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, 'male'), (1, 'female')], default=0, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='user',
            name='hobies',
            field=models.CharField(max_length=30, null=True, verbose_name='爱好'),
        ),
        migrations.AddField(
            model_name='user',
            name='intrductions',
            field=models.CharField(max_length=200, null=True, verbose_name='自我介绍'),
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ManyToManyField(blank=True, related_name='friend', to=settings.AUTH_USER_MODEL)),
                ('oner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='主人')),
            ],
            options={
                'verbose_name': '朋友管理',
                'verbose_name_plural': '朋友管理',
                'db_table': 'tb_friends',
            },
        ),
    ]
