# Generated by Django 3.2 on 2022-08-01 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schSocialMedia', '0012_auto_20220801_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='intrductions',
            new_name='instruction',
        ),
    ]
