# Generated by Django 3.2 on 2022-08-01 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schSocialMedia', '0014_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hobies',
            field=models.TextField(max_length=600, null=True, verbose_name='爱好'),
        ),
        migrations.AlterField(
            model_name='user',
            name='instruction',
            field=models.TextField(max_length=600, null=True, verbose_name='自我介绍'),
        ),
        migrations.CreateModel(
            name='MessageBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('freind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schSocialMedia.friends')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '留言版',
                'verbose_name_plural': '留言版',
                'db_table': 'tb_messageboard',
                'ordering': ['-updated', '-pub_date'],
            },
        ),
    ]
