# Generated by Django 3.2 on 2022-08-01 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schSocialMedia', '0015_auto_20220801_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageboard',
            name='freind',
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_schSocialMedia_user_friends_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
